CREATE TABLE Author (id bigint generated by default as identity, name varchar(255), contact varchar(255), primary key (id));

INSERT INTO Author(id, contact, name) VALUES(1, 'dee@duniadee.com', 'Dewi Leatari');
INSERT INTO Author(id, contact, name) VALUES(2, 'fbasuki@gmail.com', 'Fira Basuki');
INSERT INTO Author(id, contact, name) VALUES(3, '012345678', 'Mahesa Jenar');
INSERT INTO Author(id, contact, name) VALUES(4, 'pram@mizan.com', 'Pramudya D');

CREATE TABLE Publisher (id bigint generated by default as identity, name varchar(255), address varchar(255), phone varchar(255),primary key (id));

INSERT INTO Publisher(id, name, address, phone) VALUES(1, 'Gramedia', 'Jl. Palmerah', '021-345678');
INSERT INTO Publisher(id, name, address, phone) VALUES(2, 'Kompas', 'Jl. Pahlawan', '021-675678');
INSERT INTO Publisher(id, name, address, phone) VALUES(3, 'Mizan', 'Jl. Pajang', '021-675673');
INSERT INTO Publisher(id, name, address, phone) VALUES(4, 'Truffle', 'Jl. Merdeka', '021-234567');


CREATE TABLE Category (id bigint generated by default as identity, name varchar(255), description varchar(255), primary key (id));

INSERT INTO Category(id, name, description) VALUES(1, 'fiction', 'it is a novel fiction');
INSERT INTO Category(id, name, description) VALUES(2, 'manga', 'japanese comic');
INSERT INTO Category(id, name, description) VALUES(3, 'history', 'world history');
INSERT INTO Category(id, name, description) VALUES(4, 'culture', 'world culture');